In [1]:
result = 0 

In [2]:
def add(num):
    global result 
    result += num
    return result 

In [3]:
print(add(3))
print(add(4)) 

3
7


In [9]:
result1 = 0
result2 = 0

In [10]:
def add1(num):
    global result1 
    result1 += num
    return result1 

def add2(num):
    global result2 
    result2 += num
    return result2 

In [11]:
print(add1(3))
print(add1(4))
print(add2(3))
print(add2(7)) 

3
7
3
10


In [12]:
class Calculator: # class : 똑같은 무엇인가를 계속해서 만들어낼 수 있는 틀
    def __init__(self):
        self.result = 0
    
    def add(self, num):
        self.result += num
        return self.result 

In [15]:
cal1 = Calculator() # -> object : cal1 
cal2 = Calculator() # -> object : cal2

# object들간 서로 영향 없다

In [16]:
print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10


In [21]:
class FourCal:
    pass 

In [22]:
a = FourCal()
type(a) 

__main__.FourCal

linear Regression 

In [26]:
import torch 
import torch.nn as nn # nn is class
import torch.nn.functional as F # Function
import torch.optim as optim 


In [27]:
torch.manual_seed(1) 

In [24]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]]) 

오차제곱합에 대한 평균 : 평균 제곱 오차 MSE(Mean Squared Error)

In [28]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [29]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [30]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True) 
# 가중치 W를 출력
print(W) 

tensor([0.], requires_grad=True)


In [31]:
# 편향 b도 0으로 초기화함
b = torch.zeros(1,requires_grad=True)
print(b) 

tensor([0.], requires_grad=True)


In [32]:
hypothesis = x_train*W +b
print(hypothesis) 

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [33]:
# cost function
cost = torch.mean((hypothesis - y_train)**2)
print(cost) 

tensor(18.6667, grad_fn=<MeanBackward0>)


In [34]:
optimizer = optim.Adam([W,b], lr=0.01)

In [35]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

In [39]:
#  optimizer.zero_grad() -- ? : 미분을 통해 얻은 기울기를 이전에 계산된 값에 누적시키기 때문
import torch 

w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20 

for epoch in range(nb_epochs + 1):

    z = 2*w

    z.backward()
    print('수식을 W로 미분한 값 : {}'.format(w.grad)) 

수식을 W로 미분한 값 : 2.0
수식을 W로 미분한 값 : 4.0
수식을 W로 미분한 값 : 6.0
수식을 W로 미분한 값 : 8.0
수식을 W로 미분한 값 : 10.0
수식을 W로 미분한 값 : 12.0
수식을 W로 미분한 값 : 14.0
수식을 W로 미분한 값 : 16.0
수식을 W로 미분한 값 : 18.0
수식을 W로 미분한 값 : 20.0
수식을 W로 미분한 값 : 22.0
수식을 W로 미분한 값 : 24.0
수식을 W로 미분한 값 : 26.0
수식을 W로 미분한 값 : 28.0
수식을 W로 미분한 값 : 30.0
수식을 W로 미분한 값 : 32.0
수식을 W로 미분한 값 : 34.0
수식을 W로 미분한 값 : 36.0
수식을 W로 미분한 값 : 38.0
수식을 W로 미분한 값 : 40.0
수식을 W로 미분한 값 : 42.0


Multivariable Linear Regression

In [40]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670898
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.482086
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

nn.module

In [42]:
import torch
import torch.nn as nn
import torch.nn.functional as F  

In [43]:
torch.manual_seed(1) 