In [1]:
import torch 
import torchvision
import math 
import numpy as np 

In [2]:
#Numpy로 1차원 tensor making

t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t) 

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
# 1dim vector // size print 

print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape) 

Rank of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) 

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [5]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) 

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [6]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t) 

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [7]:
print('Rank of t : ', t.ndim) # print t's dimension 
print('Shape of t : ', t.shape) # print t's shape

Rank of t :  2
Shape of t :  (4, 3)


In [8]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t) 

tensor([0., 1., 2., 3., 4., 5., 6.])


In [9]:
print(t.dim())
print(t.shape)
print(t.size()) 

1
torch.Size([7])
torch.Size([7])


In [10]:
print(t[0],t[1],t[-1])
print(t[2:5], t[4:-1])
print(t[:2],t[3:]) 

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [11]:
t = torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t) 

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [12]:
print(t.dim())  
print(t.size())

2
torch.Size([4, 3])


In [13]:
print(t[:,1])
print(t[:,1].size()) 

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [14]:
print(t[:,:-1])  # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.``

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


파이토치에서는 자동으로 크기를 맞춰서 연산을 수행하게 만드는 브로드캐스팅이라는 기능을 제공

In [15]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2) 

tensor([[5., 5.]])


In [16]:
m1 = torch.FloatTensor([[1,2]]) # size : (1,2)
m2 = torch.FloatTensor([3]) # size : (1,)
print(m1 + m2) 

tensor([[4., 5.]])


In [17]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2) 

tensor([[4., 5.],
        [5., 6.]])


In [18]:
m1 = torch.FloatTensor([[1,2],[3,4]]) # 2X2
m2 = torch.FloatTensor([[1],[2]]) # 2X1
print('Shape of matrix 1 : ', m1.shape)
print('Shape of Matrix 2 : ', m2.shape)
print(m1.matmul(m2)) # 2X1 

Shape of matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [19]:
m1 = torch.FloatTensor([[1,2],[3,4]]) #element-wise 곱
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1 : ', m1.shape)
print('Shape of Matrix 2 : ', m2.shape)
print(m1*m2)
print(m1.mul(m2)) 

Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [20]:
t = torch.FloatTensor([1,2])
print(t.mean())  


tensor(1.5000)


In [21]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t) 

tensor([[1., 2.],
        [3., 4.]])


In [22]:
print(t.mean()) 

tensor(2.5000)


In [23]:
print(t.mean(dim=0)) 

tensor([2., 3.])


In [24]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t) 

tensor([[1., 2.],
        [3., 4.]])


In [25]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1]) 

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


Tensor Manipulation

In [26]:
# view
t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
ft = torch.FloatTensor(t)  
print(ft.shape) 

torch.Size([2, 2, 3])


In [27]:
# t transport to 2dim : -1 : pytorch가 알아서 // (?,3)차원으로 변경해라
print(ft.view([-1,3])) 
print(ft.view([-1,3]).shape) 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [28]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape) 

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [29]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape) 

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [30]:
# squeeze : 1인 차원을 del 
print(ft.squeeze())
print(ft.squeeze().shape) 

tensor([0., 1., 2.])
torch.Size([3])


In [31]:
# unsqueeze : 특정 위치에 1인 차원을 add 
ft = torch.Tensor([0,1,2])
print(ft.shape) 

torch.Size([3])


In [32]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape) 

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [33]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape) 

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [34]:
print(ft.unsqueeze(1)) # 인덱스가 0부터 시작하지만 두 번쨰 차원에 1을 추가하려 함 
print(ft.unsqueeze(1).shape) 

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [35]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape) 

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


Type Casting 

In [36]:
lt = torch.LongTensor([1,2,3,4])
print(lt) 

tensor([1, 2, 3, 4])


In [37]:
# float으로 type change
print(lt.float()) 

tensor([1., 2., 3., 4.])


In [38]:
bt = torch.ByteTensor([True, False, False, True])
print(bt) 

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [39]:
print(bt.long())
print(bt.float()) 

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [40]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]]) 

In [41]:
print(torch.cat([x,y], dim=0)) # 위아래로 concatenate

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [42]:
print(torch.cat([x,y], dim=1)) # x를 기준으로 y를 오른쪽에 concatenate  

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


Stacking

In [43]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [44]:
print(torch.stack([x,y,z])) 

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [45]:
print(torch.stack([x,y,z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


Ones_like & Zeros_like 

In [47]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x) 

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [48]:
# 동일한 크기(shape)지만 1로 채움
print(torch.ones_like(x)) 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [49]:
# 동일한 크기(shape)지만 0으로 채움
print(torch.zeros_like(x)) 

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In-place Operation

In [50]:
x = torch.FloatTensor([[1,2],[3,4]])

In [51]:
print(x.mul(2.)) # x에 2곱함
print(x) 

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [52]:
print(x.mul_(2.)) # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) 

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
